(function(root){
'use strict';
const SIZE={width:1400,height:1100},sites={townHall:{x:720,y:390},meson:{x:850,y:545},smithy:{x:565,y:480},carpenter:{x:570,y:650},guildHall:{x:880,y:810},textile:{x:985,y:735},forest:{x:190,y:215},hills:{x:1180,y:230},mine:{x:1210,y:410},center:{x:710,y:570}};
const names={'Ayuntamiento':'townHall','Mesón':'meson','Herrería':'smithy','Carpintería':'carpenter','Sede del Gremio':'guildHall','Textilería':'textile'};
const cam={x:0,y:0,scale:.65},points=new Map(),tokens=new Map(),visits=new Map();
let viewport,plane,people,story,initialized=false,dragged=false,gesture=null,latestEvent='',stateNow,worldNow,designNow;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function landscape(){
 const trees=Array.from({length:70},(_,i)=>{const x=70+(i*67)%360,y=65+(i*43)%330;return `<g transform="translate(${x},${y})"><ellipse cy="20" rx="20" ry="8" fill="#203729" opacity=".25"/><rect x="-3" y="-5" width="6" height="24" fill="#65442a"/><path d="M0 -45L-21 2H21Z M0 -25L-25 14H25Z" fill="${i%2?'#385c38':'#42663a'}"/></g>`;}).join('');
 const rocks=Array.from({length:15},(_,i)=>`<path d="M${1080+i%5*45} ${115+Math.floor(i/5)*55}l-24 34 18 20 38-10 6-22-18-25z" fill="#757369" stroke="#535950" stroke-width="3"/>`).join('');
 return `<svg class="city-landscape" viewBox="0 0 1400 1100" aria-hidden="true"><defs><radialGradient id="grass"><stop stop-color="#748454"/><stop offset="1" stop-color="#3b5138"/></radialGradient><pattern id="fields" width="90" height="80" patternUnits="userSpaceOnUse"><path d="M15 15l4-6m18 34l7-3m24 15l4-8" stroke="#869363" opacity=".2"/></pattern></defs><rect width="1400" height="1100" fill="url(#grass)"/><rect width="1400" height="1100" fill="url(#fields)"/><path d="M30 890Q300 725 230 560T320 30" fill="none" stroke="#3c7071" stroke-width="55"/><path d="M25 875Q282 721 218 560T310 30" fill="none" stroke="#659498" stroke-width="8" opacity=".7"/><path d="M710 570L190 215M710 570L1180 230M710 570L1210 410M565 480L850 545L880 810L570 650L565 480M880 810L985 735M720 390L710 570" stroke="#536041" stroke-width="47" fill="none"/><path d="M710 570L190 215M710 570L1180 230M710 570L1210 410M565 480L850 545L880 810L570 650L565 480M880 810L985 735M720 390L710 570" stroke="#b7a17a" stroke-width="32" fill="none"/><path d="M710 570L190 215M710 570L1180 230M710 570L1210 410" stroke="#d3bf97" stroke-width="3" stroke-dasharray="2 18" fill="none"/>${trees}${rocks}<ellipse cx="710" cy="570" rx="85" ry="45" fill="#c2b18c" stroke="#776b50" stroke-width="6"/><ellipse cx="710" cy="562" rx="23" ry="14" fill="#587e80" stroke="#938d77" stroke-width="9"/><path d="M710 550v-30" stroke="#b2aca0" stroke-width="7"/><path d="M1200 410q-30-70 30-70t30 70" fill="#28302b" stroke="#7a7462" stroke-width="16"/></svg>`;
}
function fit(){cam.scale=.65;cam.x=viewport.clientWidth/2-sites.center.x*cam.scale;cam.y=viewport.clientHeight/2-sites.center.y*cam.scale;apply();}
function apply(){const w=viewport.clientWidth,h=viewport.clientHeight;cam.x=Math.max(w*.25-SIZE.width*cam.scale,Math.min(w*.75,cam.x));cam.y=Math.max(h*.25-SIZE.height*cam.scale,Math.min(h*.75,cam.y));plane.style.transform=`translate(${cam.x}px,${cam.y}px) scale(${cam.scale})`;viewport.dataset.cameraScale=cam.scale.toFixed(3);viewport.dataset.cameraX=cam.x.toFixed(1);}
function pair(){return [...points.values()].slice(0,2);}
function startGesture(){const ps=pair();if(ps.length===2){gesture={kind:'pinch',distance:Math.hypot(ps[1].x-ps[0].x,ps[1].y-ps[0].y),center:{x:(ps[0].x+ps[1].x)/2,y:(ps[0].y+ps[1].y)/2},x:cam.x,y:cam.y,scale:cam.scale};dragged=true;}else if(ps.length===1)gesture={kind:'pan',point:ps[0],x:cam.x,y:cam.y};else gesture=null;}
function init(actions){
 viewport=document.querySelector('.city-stage');if(!viewport)return;viewport.id='cityViewport';viewport.setAttribute('aria-label','Mapa de la ciudad. Arrastrá con un dedo y usá dos dedos para zoom.');
 const buildings=[...viewport.querySelectorAll('[data-building]')];viewport.replaceChildren();
 plane=document.createElement('div');plane.id='cityPlane';plane.className='city-plane';plane.innerHTML=landscape();viewport.append(plane);
 for(const b of buildings){const key=names[b.dataset.building];b.dataset.site=key;b.style.setProperty('left',sites[key].x+'px','important');b.style.setProperty('top',sites[key].y+'px','important');plane.append(b);}
 for(const [key,label] of [['forest','Bosque del Norte'],['hills','Colinas Pedregosas'],['mine','Veta Dura']]){const node=document.createElement('button');node.className='zone-marker';node.style.left=sites[key].x+'px';node.style.top=sites[key].y+'px';node.textContent=label;node.addEventListener('click',()=>actions.open('map'));plane.append(node);}
 people=document.createElement('div');people.className='city-people';plane.append(people);
 const tools=document.createElement('div');tools.className='city-camera-tools city-overlay';tools.innerHTML='<button class="small-action" id="cityRecenter">Centrar ciudad</button><button class="small-action" id="cityStoryToggle" aria-expanded="false">Crónica</button><small>1 dedo: mover · 2 dedos: zoom</small>';viewport.parentElement.append(tools);
 document.getElementById('cityRecenter').addEventListener('click',fit);
 story=document.createElement('article');story.className='city-story-panel city-overlay';story.hidden=true;story.innerHTML='<h3>La vida de tu ciudad</h3><div id="cityStoryEvents"></div>';viewport.parentElement.append(story);
 document.getElementById('cityStoryToggle').addEventListener('click',()=>{story.hidden=!story.hidden;document.getElementById('cityStoryToggle').setAttribute('aria-expanded',String(!story.hidden));});
 viewport.addEventListener('pointerdown',e=>{if(e.button!==0)return;const rect=viewport.getBoundingClientRect();if(!points.size)dragged=false;points.set(e.pointerId,{x:e.clientX-rect.left,y:e.clientY-rect.top});if(points.size>1)for(const id of points.keys())try{viewport.setPointerCapture(id);}catch{}startGesture();});
 viewport.addEventListener('pointermove',e=>{if(!points.has(e.pointerId)||!gesture)return;const rect=viewport.getBoundingClientRect();points.set(e.pointerId,{x:e.clientX-rect.left,y:e.clientY-rect.top});const ps=pair();if(gesture.kind==='pinch'&&ps.length===2){const distance=Math.hypot(ps[1].x-ps[0].x,ps[1].y-ps[0].y),cx=(ps[0].x+ps[1].x)/2,cy=(ps[0].y+ps[1].y)/2;cam.scale=Math.max(.35,Math.min(1.5,gesture.scale*distance/Math.max(1,gesture.distance)));const ratio=cam.scale/gesture.scale;cam.x=cx-(gesture.center.x-gesture.x)*ratio;cam.y=cy-(gesture.center.y-gesture.y)*ratio;apply();}else if(ps.length===1){const dx=ps[0].x-gesture.point.x,dy=ps[0].y-gesture.point.y;if(Math.hypot(dx,dy)>7)dragged=true;if(dragged){try{viewport.setPointerCapture(e.pointerId);}catch{}cam.x=gesture.x+dx;cam.y=gesture.y+dy;apply();}}});
 const end=e=>{points.delete(e.pointerId);startGesture();};viewport.addEventListener('pointerup',end);viewport.addEventListener('pointercancel',end);
 viewport.addEventListener('click',e=>{if(dragged){e.preventDefault();e.stopImmediatePropagation();dragged=false;}},true);
 viewport.addEventListener('wheel',e=>{e.preventDefault();const r=viewport.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,old=cam.scale;cam.scale=Math.max(.35,Math.min(1.5,cam.scale*Math.exp(-e.deltaY*.001)));cam.x=x-(x-cam.x)*cam.scale/old;cam.y=y-(y-cam.y)*cam.scale/old;apply();},{passive:false});
 new ResizeObserver(()=>{if(!initialized&&viewport.clientWidth){fit();initialized=true;}else if(viewport.clientWidth)apply();}).observe(viewport);
 document.addEventListener('visibilitychange',()=>{points.clear();gesture=null;});
}
function icon(role){return role==='warrior'?'⚔':role==='explorer'?'➶':role==='healer'?'✚':role==='mage'?'✦':'⚒';}
function token(id,name,role){if(tokens.has(id))return tokens.get(id);const node=document.createElement('button');node.className='city-person '+role;node.dataset.personId=id;node.innerHTML=`<span class="person-head"></span><span class="person-body">${icon(role)}</span><small></small>`;node.querySelector('small').textContent=name;node.addEventListener('click',()=>showPerson(id));people.append(node);tokens.set(id,node);return node;}
function showPerson(id){const n=stateNow.adventurers.find(n=>n.id===id),w=stateNow.workers[id];let dialog=document.getElementById('cityPersonDialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='cityPersonDialog';dialog.className='city-person-dialog';document.body.append(dialog);}dialog.innerHTML=`<button class="small-action dialog-close">Cerrar</button><h3>${esc(n?.fullName||w?.name||w?.profession||'Mara')}</h3>${n?`<p>${esc(n.role)} · Nv.${n.level} · ${esc(n.status)}</p><p>Vida ${n.hpCurrent}/${n.hpMax} · Maná ${n.manaCurrent}/${n.manaMax}</p><p>Dinero propio: ${n.coins} monedas · Origen: ${esc(n.originCityName)}</p><p>Equipo: ${Object.values(n.equipment).filter(Boolean).map(e=>esc(e.name)+' · '+esc(e.qualityLabel||'Fundador')).join(', ')}</p><p>Botín propio: ${Object.entries(n.loot).filter(([,v])=>v>0).map(([k,v])=>v+' '+esc(designNow.resources[k]?.name||k)).join(', ')||'Sin botín'}</p><p>${n.history.activities} salidas · ${n.history.victories} victorias · ${n.history.meals} comidas · ${n.history.repairs} reparaciones</p>`:`<p>Resistencia ${Math.round(w?.stamina||0)}/100 · ${w?.currentJob?'En salida':w?.restingAtInn?'Descansando':'En la ciudad'}</p>`}`;dialog.querySelector('button').addEventListener('click',()=>dialog.close());dialog.showModal();}
function travel(start,end,p){let f=p<.22?p/.22:p>.78?(1-p)/.22:1;f=Math.max(0,Math.min(1,f));return {x:start.x+(end.x-start.x)*f,y:start.y+(end.y-start.y)*f};}
function place(node,point,status){node.style.transform=`translate(${point.x}px,${point.y}px)`;node.dataset.status=status;node.title=node.querySelector('small').textContent+' · '+status;}
function render(state,design,world){if(!viewport)return;stateNow=state;worldNow=world;designNow=design;
 const stamp=state.worldSystems.chronology.events[0]?.id||state.worldSystems.chronology.events[0]?.atMinute+':'+state.worldSystems.chronology.events[0]?.text;
 if(stamp!==latestEvent){latestEvent=stamp;const now=performance.now();for(const e of state.worldSystems.chronology.events.slice(0,5)){const n=state.adventurers.find(n=>e.adventurerId===n.id||e.text.includes(n.fullName));if(!n||e.atMinute<state.worldSystems.clockMinutes-10)continue;const site=e.type==='market'?e.shop:{repair:'smithy',service:'smithy',meson:'meson',loot:'townHall',guild:'guildHall'}[e.type];if(site)visits.set(n.id,{site,expires:now+6000});}}
 const present=new Set();
 state.adventurers.forEach((n,i)=>{present.add(n.id);const node=token(n.id,n.firstName||n.fullName.split(' ')[0],n.classKey),a=n.autonomy.currentActivity;let pos={x:sites.meson.x-80+i*38,y:sites.meson.y+50},status=n.status;
 if(a&&a.kind!=='recovery'){const end=a.kind==='delivery'?sites.guildHall:a.enemyKey==='wolf'||a.enemyKey==='alphaWolf'?sites.forest:sites.hills;const p=world.activityProgress(state,a).percent/100;pos=travel(sites.center,end,p);pos.x+=(i%3)*18;pos.y+=Math.floor(i/3)*18;status=p<.22?'De camino':p>.78?'Regresando':a.kind==='group'?'Grupo en expedición':'En actividad';node.classList.add('is-moving');}else{node.classList.remove('is-moving');const visit=visits.get(n.id);if(visit?.expires>performance.now()){pos={x:sites[visit.site].x-20+i*16,y:sites[visit.site].y+65};status='Visita reciente';}if(a?.kind==='recovery')status='Convalecencia en el Mesón';}
 node.classList.toggle('is-hurt',n.hpCurrent<n.hpMax*.4);place(node,pos,status);node.setAttribute('aria-label',n.fullName+' · '+status+' · Vida '+n.hpCurrent+'/'+n.hpMax);});
 const jobs=state.worldSystems.map.workerJobs;
 for(const [key,site,kind] of [['borin','smithy',null],['eldon','carpenter',null],['nara','meson',null],['mara','center','mine'],['logger','center','wood'],['hunter','center','hunt']]){const w=state.workers[key];present.add(key);const node=token(key,w.name||w.profession||'Mara','worker'),job=jobs.find(j=>j.kind===kind);const workerSpots={borin:{x:665,y:510},eldon:{x:670,y:670},nara:{x:930,y:575},mara:{x:655,y:600},logger:{x:700,y:625},hunter:{x:745,y:615}};let pos=workerSpots[key],status=w.restingAtInn?'Descansando':'En la ciudad';if(job){pos=travel(sites.center,kind==='mine'?sites.mine:sites.forest,world.activityProgress(state,job).percent/100);status='Trabajando fuera';}else if(w.escortMissionId){const escort=state.adventurers.find(n=>n.autonomy.currentActivity?.missionId===w.escortMissionId);if(escort){pos=travel(sites.center,kind==='mine'?sites.mine:sites.forest,world.activityProgress(state,escort.autonomy.currentActivity).percent/100);status='Con escolta';}}else if(w.restingAtInn)pos={x:sites.meson.x-80,y:sites.meson.y+95};node.classList.toggle('is-moving',!!job);place(node,pos,status);}
 for(const [id,node] of tokens)if(!present.has(id)){node.remove();tokens.delete(id);}
 for(const b of plane.querySelectorAll('[data-site]')){const key=b.dataset.site;const busy=state.worldSystems.production.queue.some(j=>j.shop===key||key==='meson'&&j.shop==='meson');b.classList.toggle('is-working',busy);b.querySelector('small').textContent=key==='textile'&&!state.worldSystems.textile.built?'Construir':'Nv. '+(state.buildings[key]?.level||1);}
 const history=[...(state.worldSystems.chronology.highlights||[]),...state.worldSystems.chronology.events.filter(e=>!['queue','kitchen','worker-start'].includes(e.type))].filter((e,i,list)=>list.findIndex(x=>x.id===e.id)===i).sort((a,b)=>b.atMinute-a.atMinute).slice(0,15);
 const feed=story.querySelector('#cityStoryEvents');const feedSign=history.map(e=>e.id||e.text).join('|');if(feed.dataset.signature!==feedSign){feed.dataset.signature=feedSign;feed.innerHTML=history.map(e=>`<p><small>${world.formatWorldTime(e.atMinute)}</small><strong>${esc(e.text)}</strong></p>`).join('')||'<p>Tu ciudad acaba de nacer. Sus primeros acontecimientos aparecerán aquí.</p>';}
 const recent=document.getElementById('cityRecentActivity');if(recent){const active=state.adventurers.filter(n=>n.autonomy.currentActivity&&n.autonomy.currentActivity.kind!=='recovery').length;const latest=state.worldSystems.chronology.events.find(e=>!['queue','kitchen','worker-start'].includes(e.type));const summary=active+' aventureros fuera · '+jobs.length+' trabajadores en salida · '+state.worldSystems.production.queue.length+' trabajos en cola';const content=summary+'|'+(latest?.text||'');{recent.dataset.summary=content;recent.innerHTML='<small>'+esc(summary)+'</small>'+(latest?'<p>'+esc(latest.text)+'</p>':'');}}
}
root.PG_CITY_LIFE={init,render,camera:()=>({...cam})};
})(globalThis);
